#!/bin/bash
set -e

echo "╔══════════════════════════════════════════╗"
echo "║  NeoSync™ — Deploy Script                ║"
echo "║  TAURUS AI CORP - FZCO                   ║"
echo "╚══════════════════════════════════════════╝"
echo ""

SCOPE="taurus-s-projects"
API_URL=""
WEB_URL=""

# Deploy API
echo "→ Deploying API..."
API_OUTPUT=$(cd api && vercel deploy --prod --yes --scope "$SCOPE" 2>&1)
API_URL=$(echo "$API_OUTPUT" | grep -oP 'https://api-[^ ]+\.vercel\.app' | head -1 || echo "$API_OUTPUT" | grep -oP 'https://api-beryl[^ ]+\.vercel\.app' | head -1)
echo "✅ API deployed: $API_URL"
echo ""

# Update frontend env with new API URL
echo "→ Updating frontend .env with API URL..."
cat > web/.env << EOF
# Auto-generated by deploy.sh — DO NOT EDIT
VITE_API_URL=$API_URL
EOF
echo "✅ Frontend .env updated"
echo ""

# Deploy Frontend
echo "→ Deploying frontend..."
WEB_OUTPUT=$(cd web && vercel deploy --prod --yes --scope "$SCOPE" 2>&1)
WEB_URL=$(echo "$WEB_OUTPUT" | grep -oP 'https://neosync-dashboard[^ ]+\.vercel\.app' | head -1 || echo "https://neosync-dashboard.vercel.app")
echo "✅ Frontend deployed: $WEB_URL"
echo ""

# Verify
echo "→ Verifying deployment..."
sleep 2
HEALTH=$(curl -s "$API_URL/health" 2>/dev/null || echo "failed")
echo "  API health: $HEALTH"
FRONTEND=$(curl -sI "$WEB_URL" 2>/dev/null | head -1 | tr -d '\r')
echo "  Frontend: $FRONTEND"
echo ""

echo "╔══════════════════════════════════════════╗"
echo "║  Deployment Complete!                    ║"
echo "╠══════════════════════════════════════════╣"
echo "║  Frontend: $WEB_URL"
echo "║  API:      $API_URL"
echo "╚══════════════════════════════════════════╝"
