import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';

// Mock AI agent - In production, this would call Gemini/Nemotron APIs
export async function POST(request: NextRequest) {
  const { userId } = await auth();
  
  if (!userId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const { topic, keywords = [] } = await request.json();

    if (!topic) {
      return NextResponse.json({ error: 'Topic is required' }, { status: 400 });
    }

    const blogPost = {
      id: `blog_${Date.now()}`,
      title: `The Ultimate Guide to ${topic}`,
      content: `This is a comprehensive guide about ${topic} covering ${keywords.join(', ')}. Generated by TAURUS AI agents powered by Gemini 1.5 Pro.`,
      keywords,
      wordCount: Math.floor(Math.random() * 500) + 500,
      generatedAt: new Date().toISOString(),
      agent: 'BizFlow SEO Agent',
      model: 'Gemini 1.5 Pro',
      userId
    };

    return NextResponse.json({ success: true, data: blogPost });
  } catch (error) {
    return NextResponse.json({ error: 'Failed to generate SEO blog' }, { status: 500 });
  }
}