-- Nexus Social Suite Dashboard — Initial Schema
-- TAURUS AI CORP - FZCO | PostgreSQL 17 + pgvector
-- Migration: 001_initial_schema

-- Enable pgvector extension for content embeddings
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

-- ── USERS ──
CREATE TABLE IF NOT EXISTS users (
    id          SERIAL PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    hashed_password VARCHAR(255) NOT NULL,
    role        VARCHAR(50) NOT NULL DEFAULT 'employee',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── CAMPAIGNS ──
CREATE TABLE IF NOT EXISTS campaigns (
    id              SERIAL PRIMARY KEY,
    user_id         INTEGER REFERENCES users(id) ON DELETE SET NULL,
    name            VARCHAR(500) NOT NULL,
    objective       VARCHAR(100) NOT NULL DEFAULT '',
    platform        VARCHAR(50) NOT NULL DEFAULT '',
    status          VARCHAR(50) NOT NULL DEFAULT 'draft',
    start_date      TIMESTAMPTZ,
    end_date        TIMESTAMPTZ,
    budget_daily    DECIMAL(12,2) NOT NULL DEFAULT 0,
    budget_total    DECIMAL(12,2) NOT NULL DEFAULT 0,
    targeting_json  JSONB NOT NULL DEFAULT '{}',
    creatives_json  JSONB NOT NULL DEFAULT '[]',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_campaigns_platform ON campaigns(platform);
CREATE INDEX idx_campaigns_status ON campaigns(status);
CREATE INDEX idx_campaigns_user_id ON campaigns(user_id);
CREATE INDEX idx_campaigns_created_at ON campaigns(created_at DESC);

-- ── ASSETS ──
CREATE TABLE IF NOT EXISTS assets (
    id              SERIAL PRIMARY KEY,
    user_id         INTEGER REFERENCES users(id) ON DELETE SET NULL,
    campaign_id     INTEGER REFERENCES campaigns(id) ON DELETE SET NULL,
    type            VARCHAR(50) NOT NULL DEFAULT '',
    file_path       VARCHAR(1000) NOT NULL DEFAULT '',
    meta_data       JSONB NOT NULL DEFAULT '{}',
    tags            TEXT[] NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_assets_campaign_id ON assets(campaign_id);
CREATE INDEX idx_assets_user_id ON assets(user_id);
CREATE INDEX idx_assets_created_at ON assets(created_at DESC);

-- ── ANALYTICS EVENTS (time-series) ──
CREATE TABLE IF NOT EXISTS analytics_events (
    id              BIGSERIAL PRIMARY KEY,
    time            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    campaign_id     INTEGER REFERENCES campaigns(id) ON DELETE CASCADE,
    metric_name     VARCHAR(100) NOT NULL,
    metric_value    DECIMAL(18,6) NOT NULL,
    platform        VARCHAR(50) NOT NULL DEFAULT '',
    tags            JSONB NOT NULL DEFAULT '{}'
);

CREATE INDEX idx_analytics_campaign_id ON analytics_events(campaign_id);
CREATE INDEX idx_analytics_time ON analytics_events(time DESC);
CREATE INDEX idx_analytics_metric_name ON analytics_events(metric_name);
CREATE INDEX idx_analytics_campaign_time ON analytics_events(campaign_id, time DESC);

-- ── AGENT SESSIONS ──
CREATE TABLE IF NOT EXISTS agent_sessions (
    id              SERIAL PRIMARY KEY,
    agent_type      VARCHAR(100) NOT NULL DEFAULT '',
    platform        VARCHAR(50) NOT NULL DEFAULT '',
    task_description TEXT NOT NULL DEFAULT '',
    status          VARCHAR(50) NOT NULL DEFAULT 'pending',
    input_data      JSONB NOT NULL DEFAULT '{}',
    output_data     JSONB NOT NULL DEFAULT '{}',
    priority        VARCHAR(20) NOT NULL DEFAULT 'medium',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_sessions_status ON agent_sessions(status);
CREATE INDEX idx_agent_sessions_platform ON agent_sessions(platform);
CREATE INDEX idx_agent_sessions_created_at ON agent_sessions(created_at DESC);

-- ── CONTENT EMBEDDINGS (pgvector) ──
CREATE TABLE IF NOT EXISTS content_embeddings (
    id              BIGSERIAL PRIMARY KEY,
    content_id      INTEGER NOT NULL,
    content_type    VARCHAR(50) NOT NULL,
    embedding       vector(1536),
    metadata        JSONB NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_content_embeddings_type ON content_embeddings(content_type);
CREATE INDEX idx_content_embeddings_embedding ON content_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- ── SEED: Default admin user (password: admin123) ──
INSERT INTO users (email, hashed_password, role)
VALUES ('admin@taurusai.io', '$2b$12$LJ3m4ys0Mf2a6MqKqJ0wF.X5qVqJ8qVqJ8qVqJ8qVqJ8qVqJ8qVqJ', 'admin')
ON CONFLICT (email) DO NOTHING;

-- ── SEED: Default employee user (password: employee123) ──
-- Note: actual bcrypt hash will be generated by the API lifespan seed function
-- This migration creates the schema only; API seeds users with proper bcrypt hashes
