#!/usr/bin/env python3
"""
TAURUS AI CORP - Content & Social Strategy Agent
Creates and manages content for scaling BizFlow™ across social media platforms
"""

import json

# `random` is used ONLY to pick placeholder values (sample percentages,
# timeframes, hashtags, demo company names) for marketing-copy templates
# generated by this agent. It never selects a token, id, password, nonce,
# or anything auth-adjacent, so the pseudo-RNG is intentional here, not a
# cryptographic gap. Each call site below carries a targeted S311 suppression.
import random
from dataclasses import asdict, dataclass
from datetime import datetime
from enum import Enum
from typing import Any

import redis.asyncio as redis
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from jinja2 import Template
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker


class ContentType(Enum):
    CASE_STUDY = "case_study"
    VIDEO_SCRIPT = "video_script"
    BLOG_POST = "blog_post"
    SOCIAL_POST = "social_post"
    EMAIL_TEMPLATE = "email_template"
    LANDING_PAGE_COPY = "landing_page_copy"

class BusinessVertical(Enum):
    ECOMMERCE = "ecommerce"
    SAAS = "saas"
    LOCAL_BUSINESS = "local_business"
    GENERAL = "general"

class SocialPlatform(Enum):
    LINKEDIN = "linkedin"
    TWITTER = "twitter"
    YOUTUBE = "youtube"
    INSTAGRAM = "instagram"
    TIKTOK = "tiktok"
    FACEBOOK = "facebook"

@dataclass
class ContentPiece:
    content_id: str
    title: str
    content_type: ContentType
    platform: SocialPlatform
    business_vertical: BusinessVertical
    content_body: str
    metadata: dict[str, Any]
    performance_metrics: dict[str, float]
    created_at: datetime
    scheduled_for: datetime | None = None

@dataclass
class ContentCalendar:
    month: str
    year: int
    content_schedule: dict[str, list[ContentPiece]]
    themes: list[str]
    campaign_goals: dict[str, str]

class ContentSocialStrategyAgent:
    """
    Agent responsible for:
    - Creating case studies showcasing business transformations
    - Developing social media content calendars
    - Generating video scripts, blog posts, and marketing materials
    - Building content templates for different business verticals
    """

    def __init__(self):
        self.name = "content-social-strategy"
        self.description = "Content creation for scaling BizFlow™ across social media"
        self.redis_client: redis.Redis | None = None
        self.db_session: AsyncSession | None = None
        self.content_templates = {}
        self.content_calendar = {}

    async def initialize(self, config: dict[str, Any]):
        """Initialize agent with configuration"""
        # Redis connection for content caching
        self.redis_client = redis.from_url(
            config.get('redis_url', 'redis://localhost:6379'),
            decode_responses=True
        )

        # Database connection for content storage
        engine = create_async_engine(
            config.get('database_url', 'postgresql+asyncpg://user:pass@localhost/taurus'),
            echo=config.get('debug', False)
        )
        async_session = sessionmaker(engine, class_=AsyncSession)
        self.db_session = async_session()

        # Load content templates
        await self._load_content_templates()

        # Initialize content calendar
        await self._initialize_content_calendar()

        print(f"✅ {self.name} agent initialized successfully")

    async def _load_content_templates(self):
        """Load content templates for different verticals"""
        self.content_templates = {
            "case_study": {
                "ecommerce": {
                    "template": """
# How {company_name} Increased Revenue by {percentage}% with BizFlow™

## The Challenge
{company_name}, a {industry} company, was struggling with:
- {challenge_1}
- {challenge_2}
- {challenge_3}

## The BizFlow™ Solution
Our AI-powered automation platform helped them:
- {solution_1}
- {solution_2}
- {solution_3}

## Results in {timeframe}
- 📈 Revenue: +{revenue_increase}%
- 🎯 Conversion Rate: +{conversion_increase}%
- ⚡ Response Time: -{response_time_reduction}%
- 💰 Cost Savings: ${cost_savings}

## Key Features Used
{features_list}

*"BizFlow™ transformed our entire operation. The ROI was immediate and continues to grow."* - {testimonial_author}, {title}
                    """,
                    "variables": ["company_name", "percentage", "industry", "challenge_1", "challenge_2", "challenge_3",
                                "solution_1", "solution_2", "solution_3", "timeframe", "revenue_increase",
                                "conversion_increase", "response_time_reduction", "cost_savings", "features_list",
                                "testimonial_author", "title"]
                },
                "saas": {
                    "template": """
# From {start_users} to {end_users} Users: {company_name}'s BizFlow™ Success Story

## The Scaling Challenge
{company_name}, a {saas_category} SaaS platform, needed to:
- Scale user acquisition without increasing support costs
- Automate onboarding for faster time-to-value
- Reduce churn through predictive engagement

## BizFlow™ Implementation
Our platform delivered:
- **Intelligent Lead Scoring**: {lead_scoring_improvement}% better qualified leads
- **Automated Onboarding**: {onboarding_time_reduction}% faster user activation
- **Predictive Churn Prevention**: {churn_reduction}% reduction in monthly churn

## Transformation in {timeframe}
- 👥 User Growth: {start_users} → {end_users} users
- 💎 MRR Growth: {mrr_growth}%
- ⭐ User Satisfaction: {satisfaction_score}/5.0
- 🤖 Support Automation: {automation_percentage}%

*"BizFlow™ didn't just help us scale - it made our growth sustainable and profitable."* - {ceo_name}, CEO
                    """,
                    "variables": ["start_users", "end_users", "company_name", "saas_category", "lead_scoring_improvement",
                                "onboarding_time_reduction", "churn_reduction", "timeframe", "mrr_growth",
                                "satisfaction_score", "automation_percentage", "ceo_name"]
                }
            },
            "social_post": {
                "linkedin": [
                    "🚀 Just helped another {vertical} business increase their {metric} by {percentage}% in {timeframe}.\n\nThe secret? AI-powered automation that works 24/7.\n\n{brief_case_study}\n\n#{hashtag1} #{hashtag2} #{hashtag3}",
                    "💡 Here's what {metric_type} looks like when you implement proper AI automation:\n\n✅ {benefit_1}\n✅ {benefit_2}\n✅ {benefit_3}\n\nReal results from real clients using BizFlow™.\n\n#{hashtag1} #{hashtag2}",
                    "📊 {vertical} businesses using AI automation see average improvements of:\n\n📈 {metric_1}: +{percentage_1}%\n⚡ {metric_2}: +{percentage_2}%\n💰 {metric_3}: +{percentage_3}%\n\nWhat's holding you back?\n\n#{hashtag1} #{hashtag2}"
                ],
                "twitter": [
                    "🔥 {vertical} case study:\n\n{metric} ↗️ {percentage}%\nTime saved ⏱️ {hours}hrs/week\nROI 💰 {roi}x\n\nAll with AI automation.\n\n#{hashtag1} #{hashtag2}",
                    "Another day, another {vertical} business transformed:\n\n• Before: {pain_point}\n• After: {solution_result}\n\nThe power of AI automation 🤖\n\n#{hashtag1}",
                    "Quick question: What if you could {benefit} while you sleep?\n\nThat's what our latest {vertical} client achieved.\n\nDM for the case study 📊\n\n#{hashtag1}"
                ]
            },
            "video_script": {
                "youtube": {
                    "template": """
TITLE: {title}
DURATION: {duration} minutes
VERTICAL: {business_vertical}

[HOOK - 0:00-0:15]
{hook_text}

[PROBLEM - 0:15-1:00]
{problem_description}

[SOLUTION - 1:00-3:00]
{solution_explanation}

[CASE STUDY - 3:00-5:00]
{case_study_details}

[DEMO - 5:00-7:00]
{demo_description}

[CTA - 7:00-8:00]
{call_to_action}

[END SCREEN - 8:00-8:15]
{end_screen_text}

NOTES:
- Use graphics at: {graphic_timestamps}
- B-roll suggestions: {broll_suggestions}
- SEO Tags: {seo_tags}
                    """,
                    "variables": ["title", "duration", "business_vertical", "hook_text", "problem_description",
                                "solution_explanation", "case_study_details", "demo_description", "call_to_action",
                                "end_screen_text", "graphic_timestamps", "broll_suggestions", "seo_tags"]
                }
            }
        }

    async def _initialize_content_calendar(self):
        """Initialize monthly content calendar template"""
        self.content_calendar = {
            "weekly_themes": {
                "monday": "Case Study Monday - Client Success Stories",
                "tuesday": "Tech Tuesday - BizFlow™ Feature Spotlights",
                "wednesday": "Wisdom Wednesday - Industry Insights & Trends",
                "thursday": "Transformation Thursday - Before/After Stories",
                "friday": "Feature Friday - Behind-the-Scenes Development",
                "saturday": "Saturday Spotlight - Team & Company Culture",
                "sunday": "Sunday Strategy - Thought Leadership"
            },
            "content_types_per_platform": {
                "linkedin": ["case_study", "thought_leadership", "industry_insights"],
                "twitter": ["quick_tips", "stats", "live_updates"],
                "youtube": ["deep_dives", "tutorials", "client_interviews"],
                "instagram": ["behind_scenes", "infographics", "stories"],
                "tiktok": ["quick_tips", "trending_topics", "fun_facts"]
            }
        }

    async def create_case_study(self, vertical: BusinessVertical, data: dict[str, Any]) -> ContentPiece:
        """Generate case study content for specific business vertical"""
        try:
            template_data = self.content_templates["case_study"][vertical.value]
            template = Template(template_data["template"])

            # Fill in template variables with provided data
            content_body = template.render(**data)

            content_piece = ContentPiece(
                content_id=f"case_study_{vertical.value}_{int(datetime.now().timestamp())}",
                title=f"{data.get('company_name', 'Client')} Success Story",
                content_type=ContentType.CASE_STUDY,
                platform=SocialPlatform.LINKEDIN,  # Primary platform for case studies
                business_vertical=vertical,
                content_body=content_body,
                metadata={
                    "word_count": len(content_body.split()),
                    "reading_time_minutes": len(content_body.split()) // 200,
                    "template_used": vertical.value,
                    "variables": list(data.keys())
                },
                performance_metrics={},
                created_at=datetime.now()
            )

            # Cache the content
            await self._cache_content(content_piece)

            return content_piece

        except Exception as e:
            print(f"❌ Case study creation failed: {e}")
            raise

    async def generate_social_media_posts(self, platform: SocialPlatform, vertical: BusinessVertical,
                                        count: int = 5) -> list[ContentPiece]:
        """Generate multiple social media posts for a platform and vertical"""
        try:
            posts = []
            templates = self.content_templates["social_post"][platform.value]

            for i in range(count):
                template = random.choice(templates)  # noqa: S311 -- template selection, not security-sensitive

                # Generate sample data for the template
                sample_data = await self._generate_sample_data(vertical, platform)

                # Fill template with data
                content_body = template.format(**sample_data)

                post = ContentPiece(
                    content_id=f"social_{platform.value}_{vertical.value}_{int(datetime.now().timestamp())}_{i}",
                    title=f"{platform.value.title()} Post for {vertical.value.title()}",
                    content_type=ContentType.SOCIAL_POST,
                    platform=platform,
                    business_vertical=vertical,
                    content_body=content_body,
                    metadata={
                        "character_count": len(content_body),
                        "hashtag_count": content_body.count('#'),
                        "mention_count": content_body.count('@'),
                        "template_used": templates.index(template)
                    },
                    performance_metrics={},
                    created_at=datetime.now()
                )

                posts.append(post)
                await self._cache_content(post)

            return posts

        except Exception as e:
            print(f"❌ Social media post generation failed: {e}")
            raise

    async def _generate_sample_data(self, vertical: BusinessVertical, platform: SocialPlatform) -> dict[str, Any]:
        """Generate sample data for content templates"""
        data_sets = {
            "ecommerce": {
                "vertical": "E-commerce",
                "metric": "revenue",
                "percentage": random.choice(["340", "275", "185", "420"]),  # noqa: S311
                "timeframe": random.choice(["90 days", "6 months", "4 months"]),  # noqa: S311
                "hashtag1": "EcommerceGrowth",
                "hashtag2": "AIAutomation",
                "hashtag3": "BizFlowSuccess",
                "benefit_1": "Automated inventory management",
                "benefit_2": "Personalized customer journeys",
                "benefit_3": "Smart pricing optimization",
                "hours": random.choice(["25", "30", "40"]),  # noqa: S311
                "roi": random.choice(["4.2", "5.1", "3.8"])  # noqa: S311
            },
            "saas": {
                "vertical": "SaaS",
                "metric": "user growth",
                "percentage": random.choice(["890", "650", "450", "720"]),  # noqa: S311
                "timeframe": random.choice(["6 months", "1 year", "8 months"]),  # noqa: S311
                "hashtag1": "SaaSGrowth",
                "hashtag2": "UserAcquisition",
                "hashtag3": "ChurnReduction",
                "benefit_1": "Predictive churn prevention",
                "benefit_2": "Automated onboarding flows",
                "benefit_3": "Smart feature recommendations",
                "hours": random.choice(["35", "45", "50"]),  # noqa: S311
                "roi": random.choice(["6.8", "7.2", "5.9"])  # noqa: S311
            },
            "local_business": {
                "vertical": "Local Business",
                "metric": "local traffic",
                "percentage": random.choice(["280", "195", "315", "240"]),  # noqa: S311
                "timeframe": random.choice(["3 months", "4 months", "5 months"]),  # noqa: S311
                "hashtag1": "LocalBusiness",
                "hashtag2": "CommunityGrowth",
                "hashtag3": "LocalSEO",
                "benefit_1": "Automated review management",
                "benefit_2": "Local SEO optimization",
                "benefit_3": "Community engagement campaigns",
                "hours": random.choice(["20", "25", "30"]),  # noqa: S311
                "roi": random.choice(["3.5", "4.1", "2.9"])  # noqa: S311
            }
        }

        return data_sets.get(vertical.value, data_sets["ecommerce"])

    async def create_video_script(self, platform: SocialPlatform, vertical: BusinessVertical,
                                topic: str, duration: int = 8) -> ContentPiece:
        """Create video script for specified platform and topic"""
        try:
            if platform == SocialPlatform.YOUTUBE:
                template_data = self.content_templates["video_script"]["youtube"]
                template = Template(template_data["template"])

                script_data = {
                    "title": f"How {vertical.value.title()} Businesses Are Using AI to {topic}",
                    "duration": duration,
                    "business_vertical": vertical.value,
                    "hook_text": f"What if I told you that {vertical.value} businesses are seeing {random.choice(['300%', '400%', '500%'])} growth using one simple AI trick?",  # noqa: S311
                    "problem_description": f"Most {vertical.value} businesses struggle with {topic} because they're stuck in outdated manual processes...",
                    "solution_explanation": "That's where BizFlow™ comes in. Our AI-powered platform automates everything...",
                    "case_study_details": f"Let me show you exactly how one {vertical.value} client achieved incredible results...",
                    "demo_description": "Here's a live demo of how this works in real-time...",
                    "call_to_action": "Ready to transform your business? Click the link below to get started with BizFlow™ today.",
                    "end_screen_text": "Subscribe for more AI business transformation content!",
                    "graphic_timestamps": "0:30, 1:45, 3:15, 5:30",
                    "broll_suggestions": "Dashboard screenshots, client testimonials, before/after metrics",
                    "seo_tags": f"{vertical.value}, AI automation, business growth, {topic}"
                }

                content_body = template.render(**script_data)
            else:
                # For other platforms, create shorter script
                # Sample growth figure for demo copy only, not security-sensitive.
                sample_growth = random.choice(['200%', '300%', '400%'])  # noqa: S311
                content_body = f"""
SHORT-FORM VIDEO SCRIPT - {platform.value.upper()}

HOOK (0-3s): {topic} breakthrough for {vertical.value} businesses!

PROBLEM (3-8s): Traditional methods are failing...

SOLUTION (8-20s): AI automation changes everything

RESULT (20-25s): Real client saw {sample_growth} growth

CTA (25-30s): Link in bio to learn more!

#AI #Automation #{vertical.value.title()}
                """

            script = ContentPiece(
                content_id=f"video_script_{platform.value}_{vertical.value}_{int(datetime.now().timestamp())}",
                title=f"{platform.value.title()} Script: {topic}",
                content_type=ContentType.VIDEO_SCRIPT,
                platform=platform,
                business_vertical=vertical,
                content_body=content_body,
                metadata={
                    "duration_minutes": duration,
                    "word_count": len(content_body.split()),
                    "topic": topic,
                    "script_type": "long-form" if platform == SocialPlatform.YOUTUBE else "short-form"
                },
                performance_metrics={},
                created_at=datetime.now()
            )

            await self._cache_content(script)
            return script

        except Exception as e:
            print(f"❌ Video script creation failed: {e}")
            raise

    async def generate_monthly_content_calendar(self, year: int, month: int,
                                              vertical: BusinessVertical = None) -> ContentCalendar:
        """Generate complete monthly content calendar"""
        try:
            # Calculate days in month
            if month == 12:
                next_month = datetime(year + 1, 1, 1)
            else:
                next_month = datetime(year, month + 1, 1)

            days_in_month = (next_month - datetime(year, month, 1)).days

            content_schedule = {}

            for day in range(1, days_in_month + 1):
                date = datetime(year, month, day)
                day_name = date.strftime("%A").lower()

                # Get theme for the day
                theme = self.content_calendar["weekly_themes"].get(day_name, "General Content")

                daily_content = []

                # Generate content based on day theme
                if "Case Study" in theme:
                    case_study_data = await self._generate_case_study_data(vertical or BusinessVertical.GENERAL)
                    case_study = await self.create_case_study(vertical or BusinessVertical.ECOMMERCE, case_study_data)
                    daily_content.append(case_study)

                elif "Feature" in theme or "Tech" in theme:
                    # Generate feature spotlight posts
                    posts = await self.generate_social_media_posts(
                        SocialPlatform.LINKEDIN,
                        vertical or BusinessVertical.GENERAL,
                        2
                    )
                    daily_content.extend(posts)

                elif "Wisdom" in theme or "Strategy" in theme:
                    # Generate thought leadership content
                    script = await self.create_video_script(
                        SocialPlatform.YOUTUBE,
                        vertical or BusinessVertical.GENERAL,
                        "Strategic Planning"
                    )
                    daily_content.append(script)

                content_schedule[f"{year}-{month:02d}-{day:02d}"] = daily_content

            calendar = ContentCalendar(
                month=f"{year}-{month:02d}",
                year=year,
                content_schedule=content_schedule,
                themes=list(self.content_calendar["weekly_themes"].values()),
                campaign_goals={
                    "brand_awareness": "Increase BizFlow™ brand recognition by 25%",
                    "lead_generation": "Generate 500+ qualified leads",
                    "engagement": "Achieve 15% average engagement rate",
                    "conversions": "Drive 100+ demo requests"
                }
            )

            # Cache the calendar
            await self._cache_content_calendar(calendar)

            return calendar

        except Exception as e:
            print(f"❌ Content calendar generation failed: {e}")
            raise

    async def _generate_case_study_data(self, vertical: BusinessVertical) -> dict[str, Any]:
        """Generate realistic case study data"""
        company_names = {
            "ecommerce": ["StyleHub", "TechGadgets Pro", "FreshMarket Online"],
            "saas": ["DataFlow Solutions", "CloudSync Pro", "AnalyticsMaster"],
            "local_business": ["Downtown Cafe", "Elite Fitness Center", "Neighborhood Pharmacy"]
        }

        return {
            "company_name": random.choice(company_names.get(vertical.value, ["Sample Company"])),  # noqa: S311
            "percentage": random.choice(["340", "275", "420", "185"]),  # noqa: S311
            "industry": vertical.value,
            "challenge_1": "Manual processes taking too much time",
            "challenge_2": "Poor customer engagement tracking",
            "challenge_3": "Inefficient lead management",
            "solution_1": "Automated workflow management",
            "solution_2": "AI-powered customer insights",
            "solution_3": "Intelligent lead scoring and nurturing",
            "timeframe": "90 days",
            "revenue_increase": random.choice(["340", "275", "185"]),  # noqa: S311
            "conversion_increase": random.choice(["45", "60", "35"]),  # noqa: S311
            "response_time_reduction": random.choice(["70", "65", "80"]),  # noqa: S311
            "cost_savings": f"{random.choice(['25000', '35000', '45000'])}",  # noqa: S311
            "features_list": "• AI Agent Automation\n• Lead Intelligence Pipeline\n• Multi-Channel Campaign Management",
            "testimonial_author": "Sarah Johnson",
            "title": "Marketing Director"
        }

    async def _cache_content(self, content: ContentPiece):
        """Cache content piece in Redis"""
        try:
            if self.redis_client:
                key = f"content:{content.content_type.value}:{content.content_id}"
                await self.redis_client.setex(
                    key,
                    86400,  # 24 hour TTL
                    json.dumps(asdict(content), default=str)
                )
        except Exception as e:
            print(f"⚠️ Failed to cache content: {e}")

    async def _cache_content_calendar(self, calendar: ContentCalendar):
        """Cache content calendar in Redis"""
        try:
            if self.redis_client:
                key = f"calendar:{calendar.year}:{calendar.month}"
                await self.redis_client.setex(
                    key,
                    604800,  # 7 day TTL
                    json.dumps(asdict(calendar), default=str)
                )
        except Exception as e:
            print(f"⚠️ Failed to cache calendar: {e}")

    async def get_content_analytics(self) -> dict[str, Any]:
        """Get content performance analytics"""
        try:
            if not self.redis_client:
                return {"error": "Redis not available"}

            # Get all content keys
            keys = await self.redis_client.keys("content:*")
            content_pieces = []

            for key in keys:
                data = await self.redis_client.get(key)
                if data:
                    content_pieces.append(json.loads(data))

            if not content_pieces:
                return {"message": "No content data available"}

            # Calculate analytics
            analytics = {
                "total_content_pieces": len(content_pieces),
                "content_by_type": {},
                "content_by_platform": {},
                "content_by_vertical": {},
                "average_engagement": 0,  # Would be calculated from actual metrics
                "top_performing_content": [],
                "content_health_score": 85
            }

            # Group by type, platform, vertical
            for piece in content_pieces:
                content_type = piece.get('content_type', 'unknown')
                platform = piece.get('platform', 'unknown')
                vertical = piece.get('business_vertical', 'unknown')

                analytics["content_by_type"][content_type] = analytics["content_by_type"].get(content_type, 0) + 1
                analytics["content_by_platform"][platform] = analytics["content_by_platform"].get(platform, 0) + 1
                analytics["content_by_vertical"][vertical] = analytics["content_by_vertical"].get(vertical, 0) + 1

            return analytics

        except Exception as e:
            return {"error": f"Analytics generation failed: {e}"}

# FastAPI integration
app = FastAPI(title="Content & Social Strategy Agent")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

agent = ContentSocialStrategyAgent()

@app.on_event("startup")
async def startup_event():
    config = {
        "redis_url": "redis://localhost:6379",
        "database_url": "postgresql+asyncpg://user:pass@localhost/taurus",
        "debug": True
    }
    await agent.initialize(config)

@app.post("/content/case-study")
async def create_case_study(vertical: str, data: dict):
    """Create case study for business vertical"""
    try:
        business_vertical = BusinessVertical(vertical.lower())
        content = await agent.create_case_study(business_vertical, data)
        return asdict(content)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e)) from e

@app.post("/content/social-posts")
async def generate_social_posts(platform: str, vertical: str, count: int = 5):
    """Generate social media posts"""
    try:
        social_platform = SocialPlatform(platform.lower())
        business_vertical = BusinessVertical(vertical.lower())
        posts = await agent.generate_social_media_posts(social_platform, business_vertical, count)
        return [asdict(post) for post in posts]
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e)) from e

@app.post("/content/video-script")
async def create_video_script(platform: str, vertical: str, topic: str, duration: int = 8):
    """Create video script"""
    try:
        social_platform = SocialPlatform(platform.lower())
        business_vertical = BusinessVertical(vertical.lower())
        script = await agent.create_video_script(social_platform, business_vertical, topic, duration)
        return asdict(script)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e)) from e

@app.post("/content/calendar")
async def generate_calendar(year: int, month: int, vertical: str = "general"):
    """Generate monthly content calendar"""
    try:
        business_vertical = BusinessVertical(vertical.lower()) if vertical != "general" else None
        calendar = await agent.generate_monthly_content_calendar(year, month, business_vertical)
        return asdict(calendar)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e)) from e

@app.get("/content/analytics")
async def get_analytics():
    """Get content performance analytics"""
    return await agent.get_content_analytics()

if __name__ == "__main__":
    import os

    import uvicorn
    print("🚀 Starting Content & Social Strategy Agent...")
    # Dev-only standalone entrypoint (not used by backend/main.py, which imports
    # this module's classes directly). Default to loopback; set HOST=0.0.0.0
    # explicitly only for containerized local/dev use.
    uvicorn.run(app, host=os.environ.get("HOST", "127.0.0.1"), port=8005)
