#!/bin/bash
# Environment Loader Script for MCP Integration
# Generated by Master Orchestrator - MCP Configuration Updater

# Load environment variables from master .env file
export ENV_FILE="/Users/user/Documents/TAURUS AI Corp./CURSOR Projects/TAURUS AI CORP/BizFlow-Orchestrator/agents/integrations/mcp-agents/master.env"

if [ -f "$ENV_FILE" ]; then
    echo "Loading environment variables from: $ENV_FILE"
    export $(grep -v '^#' "$ENV_FILE" | xargs)
    echo "Environment variables loaded successfully"
else
    echo "Error: Environment file not found at $ENV_FILE"
    exit 1
fi

# Start MCP servers
echo "Starting MCP servers..."

# Add your MCP server startup commands here
# Example:
# node /path/to/mcp-server-1/index.js &
# node /path/to/mcp-server-2/index.js &

echo "MCP servers started"
