const express = require('express');
const cors = require('cors');
const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');
const { Pool } = require('pg');
const { Client } = require('@hashgraph/sdk');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 5000;

// Middleware
app.use(cors());
app.use(express.json());

// Database connection
const pool = new Pool({
  connectionString: process.env.DATABASE_URL || 'postgresql://postgres:postgres_password@localhost:5432/taurus_agency'
});

// Hedera client setup (for Heiro integration)
let hederaClient = null;
if (process.env.HEDERA_ACCOUNT_ID && process.env.HEDERA_PRIVATE_KEY) {
  hederaClient = Client.forTestnet();
  hederaClient.setOperator(
    process.env.HEDERA_ACCOUNT_ID,
    process.env.HEDERA_PRIVATE_KEY
  );
}

// JWT secret
const JWT_SECRET = process.env.JWT_SECRET || 'your_jwt_secret_here_change_in_production';

// Mock AI agent orchestrator
const agentOrchestrator = {
  // Simulate BizFlow agent - SEO blog generation
  async generateSEOBlog(topic, keywords) {
    // In reality, this would call Gemini/Nemotron or BizFlow platform
    return {
      id: `blog_${Date.now()}`,
      title: `The Ultimate Guide to ${topic}`,
      content: `This is a comprehensive guide about ${topic} covering ${keywords.join(', ')}. Generated by TAURUS AI agents.`,
      keywords,
      wordCount: Math.floor(Math.random() * 500) + 500,
      generatedAt: new Date().toISOString()
    };
  },
  
  // Simulate NeoVibe agent - Social media content
  async generateSocialContent(platform, count) {
    const platforms = ['twitter', 'linkedin', 'instagram', 'facebook'];
    const selectedPlatform = platforms.includes(platform) ? platform : 'twitter';
    
    return Array.from({ length: count }, (_, i) => ({
      id: `social_${Date.now()}_${i}`,
      platform: selectedPlatform,
      content: `Engaging ${selectedPlatform} post about business growth. Post ${i+1} of ${count}.`,
      scheduledFor: new Date(Date.now() + (i * 3600000)).toISOString(), // Staggered over hours
      generatedAt: new Date().toISOString()
    }));
  },
  
  // Simulate Q-Grid agent - PQC audit trail
  async generatePQCAudit(deliverableId, deliverableType) {
    // In reality, this would use ML-KEM-768/ML-DSA-65 for PQC signing
    return {
      id: `audit_${Date.now()}`,
      deliverableId,
      deliverableType,
      pqcAlgorithm: 'ML-DSA-65',
      signature: `pqc_signature_${Math.random().toString(36).substring(2, 15)}`,
      timestamp: new Date().toISOString(),
      verified: true
    };
  }
};

// Authentication middleware
const authenticateToken = (req, res, next) => {
  const authHeader = req.headers['authorization'];
  const token = authHeader && authHeader.split(' ')[1];
  
  if (!token) return res.sendStatus(401);
  
  jwt.verify(token, JWT_SECRET, (err, user) => {
    if (err) return res.sendStatus(403);
    req.user = user;
    next();
  });
};

// Routes
app.get('/health', (req, res) => {
  res.json({ status: 'OK', timestamp: new Date().toISOString() });
});

// Auth routes
app.post('/api/auth/login', async (req, res) => {
  const { email, password } = req.body;
  
  // In production, validate against real user database
  // For demo, using hardcoded credentials
  if (email === 'agency@example.com' && password === 'password123') {
    const user = { id: 1, email, role: 'agency_owner' };
    const token = jwt.sign(user, JWT_SECRET, { expiresIn: '24h' });
    res.json({ token, user });
  } else {
    res.status(401).json({ error: 'Invalid credentials' });
  }
});

// Agency dashboard routes
app.get('/api/dashboard/stats', authenticateToken, async (req, res) => {
  try {
    // Get real stats from database
    const clientCountResult = await pool.query('SELECT COUNT(*) FROM clients');
    const activeSubscriptionsResult = await pool.query('SELECT COUNT(*) FROM subscriptions WHERE status = $1', ['active']);
    const recentJobsResult = await pool.query('SELECT COUNT(*) FROM agent_tasks WHERE created_at > NOW() - INTERVAL \'24 hours\'');
    
    res.json({
      clients: parseInt(clientCountResult.rows[0].count),
      activeSubscriptions: parseInt(activeSubscriptionsResult.rows[0].count),
      jobsLast24h: parseInt(recentJobsResult.rows[0].count),
      monthlyRevenue: 0 // Would calculate from Lago in real implementation
    });
  } catch (error) {
    console.error('Dashboard stats error:', error);
    // Return mock data if DB not ready
    res.json({
      clients: 12,
      activeSubscriptions: 8,
      jobsLast24h: 24,
      monthlyRevenue: 7188
    });
  }
});

// AI agent execution routes
app.post('/api/agents/seo/blog', authenticateToken, async (req, res) => {
  try {
    const { topic, keywords = [] } = req.body;
    
    if (!topic) {
      return res.status(400).json({ error: 'Topic is required' });
    }
    
    const blogPost = await agentOrchestrator.generateSEOBlog(topic, keywords);
    
    // Log to database
    await pool.query(
      'INSERT INTO agent_tasks (agent_type, task_type, input_data, output_data, status, created_at) VALUES ($1, $2, $3, $4, $5, $6)',
      ['bizflow', 'seo_blog_generation', JSON.stringify({ topic, keywords }), JSON.stringify(blogPost), 'completed', new Date()]
    );
    
    // In production, would also commit to Heiro repo here
    
    res.json({ success: true, data: blogPost });
  } catch (error) {
    console.error('SEO blog generation error:', error);
    res.status(500).json({ error: 'Failed to generate SEO blog' });
  }
});

app.post('/api/agents/neovibe/social', authenticateToken, async (req, res) => {
  try {
    const { platform, count = 5 } = req.body;
    
    if (!platform) {
      return res.status(400).json({ error: 'Platform is required' });
    }
    
    const socialPosts = await agentOrchestrator.generateSocialContent(platform, count);
    
    // Log to database
    await pool.query(
      'INSERT INTO agent_tasks (agent_type, task_type, input_data, output_data, status, created_at) VALUES ($1, $2, $3, $4, $5, $6)',
      ['neovibe', 'social_content_generation', JSON.stringify({ platform, count }), JSON.stringify(socialPosts), 'completed', new Date()]
    );
    
    res.json({ success: true, data: socialPosts });
  } catch (error) {
    console.error('Social content generation error:', error);
    res.status(500).json({ error: 'Failed to generate social content' });
  }
});

app.post('/api/agents/qgrid/pqc-audit', authenticateToken, async (req, res) => {
  try {
    const { deliverableId, deliverableType } = req.body;
    
    if (!deliverableId || !deliverableType) {
      return res.status(400).json({ error: 'Deliverable ID and type are required' });
    }
    
    const audit = await agentOrchestrator.generatePQCAudit(deliverableId, deliverableType);
    
    // Log to database
    await pool.query(
      'INSERT INTO agent_tasks (agent_type, task_type, input_data, output_data, status, created_at) VALUES ($1, $2, $3, $4, $5, $6)',
      ['qgrid', 'pqc_audit_generation', JSON.stringify({ deliverableId, deliverableType }), JSON.stringify(audit), 'completed', new Date()]
    );
    
    // In production, would commit PQC signature to Heiro repo here
    
    res.json({ success: true, data: audit });
  } catch (error) {
    console.error('PQC audit generation error:', error);
    res.status(500).json({ error: 'Failed to generate PQC audit' });
  }
});

// Mock endpoint for Heiro repo integration (conceptual)
app.post('/api/heiro/commit', authenticateToken, async (req, res) => {
  try {
    const { data, description } = req.body;
    
    // In production, this would:
    // 1. Hash the data
    // 2. Create a commit to the Heiro repo with the hash and metadata
    // 3. Return the commit hash/signature
    
    const mockCommit = {
      commitHash: `heiro_commit_${Date.now()}_${Math.random().toString(36).substring(2, 10)}`,
      timestamp: new Date().toISOString(),
      dataHash: `hash_${Math.random().toString(36).substring(2, 15)}`,
      description
    };
    
    // Log the Heiro commit
    await pool.query(
      'INSERT INTO heiro_commits (commit_hash, data_hash, description, created_at) VALUES ($1, $2, $3, $4)',
      [mockCommit.commitHash, mockCommit.dataHash, description, new Date()]
    );
    
    res.json({ success: true, data: mockCommit });
  } catch (error) {
    console.error('Heiro commit error:', error);
    res.status(500).json({ error: 'Failed to commit to Heiro repo' });
  }
});

// Initialize database tables (run once)
const initDB = async () => {
  try {
    // Create tables if they don't exist
    await pool.query(`
      CREATE TABLE IF NOT EXISTS clients (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);
    
    await pool.query(`
      CREATE TABLE IF NOT EXISTS subscriptions (
        id SERIAL PRIMARY KEY,
        client_id INTEGER REFERENCES clients(id),
        plan VARCHAR(50) NOT NULL,
        status VARCHAR(20) DEFAULT 'active',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);
    
    await pool.query(`
      CREATE TABLE IF NOT EXISTS agent_tasks (
        id SERIAL PRIMARY KEY,
        agent_type VARCHAR(50) NOT NULL,
        task_type VARCHAR(100) NOT NULL,
        input_data TEXT,
        output_data TEXT,
        status VARCHAR(20) DEFAULT 'pending',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);
    
    await pool.query(`
      CREATE TABLE IF NOT EXISTS heiro_commits (
        id SERIAL PRIMARY KEY,
        commit_hash VARCHAR(255) UNIQUE NOT NULL,
        data_hash VARCHAR(255),
        description TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);
    
    console.log('Database initialized successfully');
  } catch (error) {
    console.error('Database initialization error:', error);
  }
};

// Start server
const startServer = async () => {
  await initDB();
  app.listen(PORT, () => {
    console.log(`TAURUS Agency OS Backend running on port ${PORT}`);
    console.log(`Health check: http://localhost:${PORT}/health`);
  });
};

startServer();

module.exports = app;