import { PricingTierCard } from "@/components/invest/PricingTierCard";
import { LeadCaptureForm } from "@/components/contact/LeadCaptureForm";

// Mock JSON data mapping based on real-estate NRI typical investment tiers
// In production, this would be generated by parsing the INVESTORS.csv
const INVESTOR_TIERS = [
  {
    id: "tier-bronze",
    name: "Bronze - Heritage",
    price: "₹ 50 Lakhs",
    benefits: [
      "Priority Access to Premium Units",
      "Guaranteed 6% Rental Yield",
      "Complimentary Property Management for 1 Year",
      "1 Week Annual Stay in Guest Suites",
    ],
    cta: "Secure Heritage Tier",
  },
  {
    id: "tier-silver",
    name: "Silver - Legacy",
    price: "₹ 1 Crore",
    benefits: [
      "Exclusive Villa Selection",
      "Guaranteed 7.5% Rental Yield",
      "Complimentary Property Management for 3 Years",
      "3 Weeks Annual Stay in Guest Suites",
      "VIP Medical Concierge Access",
    ],
    cta: "Secure Legacy Tier",
  },
  {
    id: "tier-gold",
    name: "Gold - Dynasty",
    price: "₹ 2.5 Crores",
    benefits: [
      "Custom Estate Customization",
      "Guaranteed 9% Rental Yield",
      "Lifetime Property Management",
      "Unlimited Access to Guest Suites",
      "Dedicated On-site Caregiver Option",
      "Board of Advisers Seat",
    ],
    cta: "Secure Dynasty Tier",
  },
];

export const metadata = {
  title: "Mater Maria Homes | Secure a Legacy in Kerala",
  description: "Secure a High-Yield Asset in Kerala. Secure a World-Class Future for Your Family.",
};

export default function InvestorPage() {
  return (
    <div className="min-h-screen bg-[#00103F] text-white">
      {/* Hero Section */}
      <section className="theme-security py-24 px-6 md:px-12 text-center max-w-5xl mx-auto">
        <h1 className="text-4xl md:text-6xl font-heading font-bold mb-6 text-[#FDC420]">
          Secure a High-Yield Asset in Kerala.
        </h1>
        <h2 className="text-2xl md:text-3xl font-heading text-white/90 mb-12">
          Secure a World-Class Future for Your Family.
        </h2>
        <p className="text-lg text-white/80 max-w-3xl mx-auto mb-16">
          Invest in Kerala's premier, fully-managed senior living and heritage estate. 
          Enjoy robust returns while securing a world-class, medically-supported sanctuary 
          for your loved ones.
        </p>
      </section>

      {/* Pricing Tiers */}
      <section className="py-16 px-6 md:px-12 max-w-7xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {INVESTOR_TIERS.map((tier, index) => (
            <PricingTierCard key={tier.id} tier={tier} index={index} />
          ))}
        </div>
      </section>

      {/* Lead Capture Section */}
      <section className="theme-lifestyle py-24 px-6 md:px-12">
        <div className="max-w-4xl mx-auto text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-heading font-bold text-[#968217] mb-4">
            Request an Investor Brochure
          </h2>
          <p className="text-[#00103F]/80 text-lg">
            Connect with our legacy advisors to discuss which tier aligns with your family's vision.
          </p>
        </div>
        <LeadCaptureForm />
      </section>
    </div>
  );
}
