import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';

export async function POST(request: NextRequest) {
  const { userId } = await auth();
  
  if (!userId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const { platform, count = 5 } = await request.json();

    if (!platform) {
      return NextResponse.json({ error: 'Platform is required' }, { status: 400 });
    }

    const platforms = ['twitter', 'linkedin', 'instagram', 'facebook'];
    const selectedPlatform = platforms.includes(platform) ? platform : 'twitter';

    const socialPosts = Array.from({ length: count }, (_, i) => ({
      id: `social_${Date.now()}_${i}`,
      platform: selectedPlatform,
      content: `Engaging ${selectedPlatform} post about business growth and digital transformation. Generated by NeoVibe AI.`,
      scheduledFor: new Date(Date.now() + (i * 3600000)).toISOString(),
      generatedAt: new Date().toISOString(),
      agent: 'NeoVibe Social Agent',
      model: 'Nemotron-3',
      userId
    }));

    return NextResponse.json({ success: true, data: socialPosts });
  } catch (error) {
    return NextResponse.json({ error: 'Failed to generate social content' }, { status: 500 });
  }
}