#!/usr/bin/env python3
"""
Environment File Manager Agent
Master Orchestrator Sub-Agent for MCP API Keys Fix System

This agent standardizes environment file locations and ensures
proper .env file structure across the project.
"""

import shutil
from datetime import datetime
from pathlib import Path


class EnvironmentFileManager:
    """Manages environment file locations and standardization"""

    def __init__(self, project_root: str):
        self.project_root = Path(project_root)
        self.standard_locations = [
            self.project_root / "TAURUS AI CORP" / "BizFlow-Orchestrator" / ".env",
            self.project_root / "TAURUS AI CORP" / "BizFlow-Orchestrator" / "agents" / "integrations" / "mcp-agents" / ".env",
            self.project_root / "web-land-Dash" / ".env",
            self.project_root / "Neural-Commerce-Systems" / ".env"
        ]

        self.master_env_file = self.project_root / "TAURUS AI CORP" / "BizFlow-Orchestrator" / "agents" / "integrations" / "mcp-agents" / "master.env"

    def standardize_environment_files(self) -> dict[str, str]:
        """Standardize all environment files across the project"""
        print("📁 Starting Environment File Manager...")

        results = {
            "created_files": [],
            "updated_files": [],
            "errors": [],
            "standardized_locations": []
        }

        # Find all existing .env files
        existing_env_files = self._find_existing_env_files()
        print(f"🔍 Found {len(existing_env_files)} existing .env files")

        # Create master .env file if it doesn't exist
        if not self.master_env_file.exists():
            self._create_master_env_file()
            results["created_files"].append(str(self.master_env_file))

        # Standardize each location
        for location in self.standard_locations:
            try:
                self._standardize_location(location)
                results["standardized_locations"].append(str(location))
                print(f"✅ Standardized: {location}")
            except Exception as e:
                error_msg = f"Error standardizing {location}: {str(e)}"
                results["errors"].append(error_msg)
                print(f"❌ {error_msg}")

        # Update MCP configuration files
        self._update_mcp_configurations()

        # Generate .gitignore entries
        self._update_gitignore_files()

        return results

    def _find_existing_env_files(self) -> list[Path]:
        """Find all existing .env files in the project"""
        env_files = []

        # Search for various .env file patterns
        patterns = ["*.env", "*.env.*", ".env*"]

        for pattern in patterns:
            found_files = list(self.project_root.rglob(pattern))
            env_files.extend(found_files)

        # Remove duplicates and sort
        env_files = list(set(env_files))
        env_files.sort()

        return env_files

    def _create_master_env_file(self):
        """Create the master .env file with all required keys"""
        print("📝 Creating master .env file...")

        master_content = """# ===========================================
# TAURUS AI CORP - MASTER ENVIRONMENT FILE
# ===========================================
# This file contains all required API keys for MCP integration
# Generated by Master Orchestrator - API Keys Fix System
# Date: {date}

# ===========================================
# CRITICAL MCP API KEYS (HIGH PRIORITY)
# ===========================================

# Perplexity AI - Required for AI-powered search
PERPLEXITY_API_KEY=your_perplexity_key_here

# Firecrawl - Required for web scraping and content analysis
FIRECRAWL_API_KEY=your_firecrawl_key_here

# Anthropic Claude - Required for Claude AI integration
ANTHROPIC_API_KEY=your_anthropic_key_here

# OpenAI - Required for ChatGPT integration
OPENAI_API_KEY=your_openai_key_here

# ===========================================
# DESIGN & DEVELOPMENT TOOLS
# ===========================================

# Figma Integration
FIGMA_ACCESS_TOKEN=your_figma_token_here
FIGMA_FILE_KEY=your_figma_file_key_here

# Design Tokens Path
DESIGN_TOKENS_PATH=/Users/user/Documents/TAURUS AI Corp./CURSOR Projects/TAURUS AI CORP/BizFlow-Orchestrator/agents/integrations/mcp-agents/design-tokens-mcp/tokens

# Tailwind CSS Configuration
TAILWIND_CONFIG_PATH=/Users/user/Documents/TAURUS AI Corp./CURSOR Projects/TAURUS AI CORP/BizFlow-Orchestrator/agents/integrations/mcp-agents/tailwind-mcp/tokens

# ===========================================
# GOOGLE SERVICES
# ===========================================

# Google OAuth Credentials
GOOGLE_CLIENT_ID=your_google_client_id_here
GOOGLE_CLIENT_SECRET=your_google_client_secret_here

# ===========================================
# COMMUNICATION & COLLABORATION
# ===========================================

# Slack Integration
SLACK_BOT_TOKEN=xoxb-your-slack-bot-token-here
SLACK_USER_TOKEN=xoxp-your-slack-user-token-here

# Notion Integration
NOTION_API_KEY=secret_your_notion_api_key_here

# ===========================================
# BUSINESS & CRM TOOLS
# ===========================================

# HubSpot CRM
HUBSPOT_ACCESS_TOKEN=your_hubspot_access_token_here

# Airtable Database
AIRTABLE_ACCESS_TOKEN=your_airtable_access_token_here

# Linear Project Management
LINEAR_API_KEY=your_linear_api_key_here

# ===========================================
# WEBFLOW INTEGRATION
# ===========================================

# Webflow Configuration (Your Existing Credentials)
WEBFLOW_ACCESS_TOKEN=ded536b9e74e112707f7087c7dabe365c7e76ba0c0949e6439e57868b4e40dad
WEBFLOW_SITE_ID=your_webflow_site_id_here
WEBFLOW_CLIENT_ID=f1f4344f7074e4f1f0dd50b1b2867873c17778f877f6f7a07a7882e79bf06828
WEBFLOW_CLIENT_SECRET=a2ae2e2baa88203e069c004a0452272c1fc8f3846d8687c27de13a34a684c097
WEBFLOW_REDIRECT_URI=http://localhost:8168/callback

# ===========================================
# DEVELOPMENT TOOLS
# ===========================================

# GitHub Integration
GITHUB_PERSONAL_ACCESS_TOKEN=your_github_token_here

# ===========================================
# MCP SERVER CONFIGURATION
# ===========================================

MCP_SERVER_HOST=localhost
MCP_SERVER_PORT=8000
MCP_SERVER_DEBUG=True

# ===========================================
# LOGGING CONFIGURATION
# ===========================================

LOG_LEVEL=INFO
LOG_FILE=taurus_ai_mcp_integration.log

# ===========================================
# SECURITY NOTES
# ===========================================
# 1. Never commit this file to version control
# 2. Replace all placeholder values with real API keys
# 3. Keep this file secure and limit access
# 4. Rotate API keys regularly
# ===========================================""".format(date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

        # Ensure directory exists
        self.master_env_file.parent.mkdir(parents=True, exist_ok=True)

        # Write master .env file
        with open(self.master_env_file, 'w') as f:
            f.write(master_content)

        print(f"✅ Master .env file created: {self.master_env_file}")

    def _standardize_location(self, location: Path):
        """Standardize a specific .env file location"""
        # Ensure parent directory exists
        location.parent.mkdir(parents=True, exist_ok=True)

        # If location doesn't exist, copy from master
        if not location.exists():
            if self.master_env_file.exists():
                shutil.copy2(self.master_env_file, location)
                print(f"📋 Copied master .env to: {location}")
            else:
                # Create a basic .env file
                self._create_basic_env_file(location)
                print(f"📝 Created basic .env at: {location}")
        else:
            # Update existing file with missing keys
            self._update_existing_env_file(location)
            print(f"🔄 Updated existing .env: {location}")

    def _create_basic_env_file(self, location: Path):
        """Create a basic .env file at the specified location"""
        basic_content = """# Basic Environment Configuration
# Generated by Environment File Manager

# Critical MCP API Keys
PERPLEXITY_API_KEY=your_perplexity_key_here
FIRECRAWL_API_KEY=your_firecrawl_key_here
ANTHROPIC_API_KEY=your_anthropic_key_here
OPENAI_API_KEY=your_openai_key_here

# Add your actual API keys here
"""

        with open(location, 'w') as f:
            f.write(basic_content)

    def _update_existing_env_file(self, location: Path):
        """Update an existing .env file with missing keys"""
        # Read existing content
        with open(location) as f:
            existing_content = f.read()

        # Read master content
        if self.master_env_file.exists():
            with open(self.master_env_file) as f:
                master_content = f.read()

            # Extract keys from master that are missing in existing
            existing_keys = set()
            for line in existing_content.split('\n'):
                if '=' in line and not line.strip().startswith('#'):
                    key = line.split('=')[0].strip()
                    existing_keys.add(key)

            # Add missing keys
            missing_keys = []
            for line in master_content.split('\n'):
                if '=' in line and not line.strip().startswith('#'):
                    key = line.split('=')[0].strip()
                    if key not in existing_keys:
                        missing_keys.append(line)

            if missing_keys:
                # Append missing keys
                updated_content = existing_content + '\n\n# Added by Environment File Manager\n' + '\n'.join(missing_keys)

                with open(location, 'w') as f:
                    f.write(updated_content)

                print(f"➕ Added {len(missing_keys)} missing keys to {location}")

    def _update_mcp_configurations(self):
        """Update MCP configuration files to point to correct .env locations"""
        print("🔧 Updating MCP configurations...")

        # Find MCP config files
        mcp_config_files = list(self.project_root.rglob("*mcp*config*.json"))

        for config_file in mcp_config_files:
            try:
                self._update_mcp_config_file(config_file)
                print(f"✅ Updated MCP config: {config_file}")
            except Exception as e:
                print(f"❌ Error updating {config_file}: {e}")

    def _update_mcp_config_file(self, config_file: Path):
        """Update a specific MCP configuration file"""
        # This would involve reading the JSON config and updating environment paths
        # For now, we'll just ensure the file exists and is readable
        if config_file.exists():
            with open(config_file) as f:
                content = f.read()

            # Add comment about .env file location
            updated_content = f"// MCP Configuration - Environment file should be at: {self.master_env_file}\n{content}"

            with open(config_file, 'w') as f:
                f.write(updated_content)

    def _update_gitignore_files(self):
        """Update .gitignore files to exclude .env files"""
        print("🔒 Updating .gitignore files...")

        gitignore_entries = [
            "# Environment files",
            ".env",
            ".env.local",
            ".env.*.local",
            "*.env",
            "master.env"
        ]

        # Find all .gitignore files
        gitignore_files = list(self.project_root.rglob(".gitignore"))

        for gitignore_file in gitignore_files:
            try:
                self._update_gitignore_file(gitignore_file, gitignore_entries)
                print(f"✅ Updated .gitignore: {gitignore_file}")
            except Exception as e:
                print(f"❌ Error updating {gitignore_file}: {e}")

    def _update_gitignore_file(self, gitignore_file: Path, entries: list[str]):
        """Update a specific .gitignore file"""
        if gitignore_file.exists():
            with open(gitignore_file) as f:
                existing_content = f.read()
        else:
            existing_content = ""

        # Check if entries already exist
        missing_entries = []
        for entry in entries:
            if entry not in existing_content:
                missing_entries.append(entry)

        if missing_entries:
            updated_content = existing_content + '\n' + '\n'.join(missing_entries) + '\n'

            with open(gitignore_file, 'w') as f:
                f.write(updated_content)

            print(f"➕ Added {len(missing_entries)} entries to {gitignore_file}")

def main():
    """Main execution function"""
    project_root = "/Users/user/Documents/TAURUS AI Corp./CURSOR Projects"

    manager = EnvironmentFileManager(project_root)
    results = manager.standardize_environment_files()

    print("\n" + "="*80)
    print("📁 ENVIRONMENT FILE MANAGER RESULTS")
    print("="*80)
    print(f"✅ Created files: {len(results['created_files'])}")
    print(f"🔄 Updated files: {len(results['updated_files'])}")
    print(f"📍 Standardized locations: {len(results['standardized_locations'])}")
    print(f"❌ Errors: {len(results['errors'])}")

    if results['errors']:
        print("\n❌ ERRORS:")
        for error in results['errors']:
            print(f"   - {error}")

    return results

if __name__ == "__main__":
    main()
